#!/bin/csh
cd output

if ( -f density.pdf ) then
   echo "Removing density.pdf..."
   rm density.pdf
endif
gnuplot ../plotscripts/density.gp

if ( -f momentum.pdf ) then
   echo "Removing momentum.pdf..."
   rm momentum.pdf
endif
gnuplot ../plotscripts/momentum.gp

if ( -f energy.pdf ) then
   echo "Removing energy.pdf..."
   rm energy.pdf
endif
gnuplot ../plotscripts/energy.gp

cd ..
