#!/bin/bash
cd output

if [ -f density.pdf ]
then
   echo "Removing density.pdf..."
   rm density.pdf
fi
gnuplot ../plotscripts/density.gp

if [ -f momentum.pdf ]
then
   echo "Removing momentum.pdf..."
   rm momentum.pdf
fi
gnuplot ../plotscripts/momentum.gp

if [ -f energy.pdf ]
then
   echo "Removing energy.pdf..."
   rm energy.pdf
fi
gnuplot ../plotscripts/energy.gp

cd ..
