#!/bin/bash
#
# Usage: new_class <class name>

# check that 1 argument was provided
if [ $# -ne 1 ]; then
  echo "Usage: new_class <class name>"
else
  # copy templates
  cp templates/NewClass.h  $1.h
  cp templates/NewClass.cc $1.cc

  # substitute class name in files
  sed -i "s/NewClass/$1/g" $1.h
  sed -i "s/NewClass/$1/g" $1.cc
fi
